from PyQt5 import QtCore, QtGui, QtWidgets
from Ui_score_edit import *

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("PMT Tabler")
        Form.setFixedSize(800, 600)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget_tables = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        self.tabWidget_tables.setObjectName("tabWidget_tables")
        self.tab_tables_1 = QtWidgets.QWidget()
        self.tab_tables_1.setObjectName("tab_tables_1")
        self.tabWidget_tables.addTab(self.tab_tables_1, "")
        self.tab_tables_2 = QtWidgets.QWidget()
        self.tab_tables_2.setObjectName("tab_tables_2")
        self.tabWidget_tables.addTab(self.tab_tables_2, "")
        self.horizontalLayout_2.addWidget(self.tabWidget_tables)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(15, 50, 15, 50)
        self.verticalLayout_3.setSpacing(25)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_3.addWidget(self.pushButton_3)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 50, -1, -1)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.button_change_view = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_change_view.setObjectName("button_change_view")
        self.horizontalLayout.addWidget(self.button_change_view)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget_scores = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        self.tabWidget_scores.setObjectName("tabWidget_scores")
        self.tab_scores_1 = QtWidgets.QWidget()
        self.tab_scores_1.setObjectName("tab_scores_1")
        self.tabWidget_scores.addTab(self.tab_scores_1, "")
        self.tab_scores_2 = QtWidgets.QWidget()
        self.tab_scores_2.setObjectName("tab_scores_2")
        self.tabWidget_scores.addTab(self.tab_scores_2, "")
        self.verticalLayout.addWidget(self.tabWidget_scores)
        self.button_edit_score = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.button_edit_score.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.button_edit_score)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)

        self.button_edit_score.clicked.connect(self.score_editor)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.tabWidget_tables.setTabText(self.tabWidget_tables.indexOf(self.tab_tables_1), _translate("Form", "Tab 1"))
        self.tabWidget_tables.setTabText(self.tabWidget_tables.indexOf(self.tab_tables_2), _translate("Form", "Tab 2"))
        self.pushButton_2.setText(_translate("Form", "Настройка команд"))
        self.pushButton_3.setText(_translate("Form", "Новый тур"))
        self.pushButton_4.setText(_translate("Form", "Выход"))
        self.button_change_view.setText(_translate("Form", "Сохранить как..."))
        self.tabWidget_scores.setTabText(self.tabWidget_scores.indexOf(self.tab_scores_1), _translate("Form", "Tab 1"))
        self.tabWidget_scores.setTabText(self.tabWidget_scores.indexOf(self.tab_scores_2), _translate("Form", "Tab 2"))
        self.button_edit_score.setText(_translate("Form", "Настройка счета"))

    @staticmethod
    def score_editor():
        Widget = QtWidgets.QWidget()
        popup = Ui_Form_score_edit()
        popup.setupUi(Widget)
        Widget.show()





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())